config/routes.rb
Rails.application.routes.draw do

  get 'pages/about'

  get 'pages/contact'

  get 'pages/resources'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  match 'about', :to => 'pages#about', :via => [:get, :post]
  match 'contact', :to => 'pages#contact', :via => [:get, :post]
  match 'resources', :to => 'pages#resources', :via => [:get, :post]
  
  get 'categories/edit'

  get 'categories/new'

  get 'categories/show'

  get 'home/index'
	resources :posts
	resources :categories

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'home#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
  #attr_accessible :name
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  #attr_accessible :name, :body, :categoy_id, :author_id
  belongs_to :category
  belongs_to :admin_user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :all_categories
  helper_method :all_posts
  helper_method :all_trendingPosts
  helper_method :all_trendingCategories
  before_filter :site_search

  def all_categories
    @categories = Category.all
  end

  def all_posts
    @posts = Post.all
  end

  def all_trendingPosts
    @posts = Post.order("created_at desc").limit(4)
  end

  def all_trendingCategories
    @categories = Category.order("created_at desc").limit(4)
  end

  def site_search
    @search = Post.search(params[:q])
	  @search_posts = @search.result
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @disable_pagination = true
  end

  def show
    @category = Category.find(params[:id])
    @title = @category.name
    @posts = @category.posts
    @disable_pagination = true
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.order("created_at desc").limit(3)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @disable_pagination = true
  end

  def contact
    @disable_pagination = true
  end

  def resources
    @disable_pagination = true
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@search = Post.search(params[:q])
	  @posts = @search.result
	end

	def show
	  @posts = Post.find(params[:id])
		@user = AdminUser.all
		@disable_sidebar = true
		@disable_footer = true
		@disable_pagination = true

	end

	def new
	  @posts = Post.new
	  @category = Category.all

	end

	def create
	  @posts = Post.new(post_params)
          if @posts.save
            redirect_to posts_path, :notice=>"Your post has been saved."
          else
            render "new"

          end

	end

	def edit
	  @posts = Post.find(params[:id])
	end

	def update
	  @posts = Post.find(params[:id])
          if @posts.update_attributes(post_params)
            redirect_to post_path, :notice => "Your Post has been updated."
          else
            render "edit"
          end
	end

	def destroy
          @posts = Post.find(params[:id])

          @posts.destroy
          redirect_to posts_path, :notice => "Your Post has been deleted."
	end

	private

	def post_params
	  params.require(:post).permit(:title, :body, :category_id, :admin_user_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/index.html.haml
%h1
  Listing Categories

%ul
  - @categories.each do |cat|
    %li
      = link_to cat.name, category_path(:id => cat.id)

app/views/categories/show.html.haml
.text
  %header.published
    .title
      %h2
        = @category.name



.mini-posts#categories_layout
  - if @posts.present?
    - @posts.each do |p|
      %article.mini-post
        %header
          %h3
            = link_to p.title, p
          %a.author{:href => "#"}
            %img
              = image_tag "avatar.jpg"
        %a.image{:href => "#"}
          %img
            = image_tag "pic03.jpg"

  - else
    %p Sorry! No posts in this category.


.text
  %header
    %h3
      = link_to "Back to Categories", categories_path

app/views/home/index.html.haml
- @posts.each do |p|
  %article#posts_landing.post
    %header
      .title
        %h2
          = link_to p.title, p

        %p This is extra description.
      .meta
        %time.published
          = p.created_at.strftime("%b %d, %Y")
        %a.author{:href => "#"}
          %span.name
            = p.admin_user.name
          %img
            = image_tag "avatar.jpg"
    %a.image.featured{:href => "#"}
      %img
        = image_tag "pic01.jpg"
    %p
      = p.body
    %footer
      %ul.actions
        %li
          .button.big
            = link_to "Continue Reading", p
      %ul.stats
        %li
          = link_to p.category.name, category_path(:id => p.category.id)
        %li
          %a.icon.fa-heart{:href => "#"} 28
        %li
          %a.icon.fa-comment{:href => "#"} 128

app/views/layouts/application.html.erb
<%= render "partials/header" %>
					<section id="menu">

							<section>
								<form class="search" method="get" action="#">
									<input type="text" name="query" placeholder="Search" />
								</form>
							</section>
							<section>
								<ul class="links">
									<li>
										<a href="#">
											<h3>Home</h3>
											<p>Checkout latest entries</p>
										</a>
									</li>

									<li>
										<a href="#">
											<h3>All Posts</h3>
											<p>Collection of all the articles</p>
										</a>
									</li>
								</ul>
							</section>

							<section>
								<ul class="actions vertical">
									<li><%= link_to "Log In", admin_root_path, class: "button big fit" %></li>
								</ul>
							</section>

					</section>

					<div>
						<% flash.each do |key, value| %>

						<p><%= value %> </p>
						<% end %>
					</div>

				<!-- Main -->
					<div id="main">
						<%= yield %>

						<!-- Pagination -->
						<%= render "partials/pagination" unless @disable_pagination %>

					</div>

          <!-- Sidebar -->
          <%= render "partials/sidebar" unless @disable_sidebar%>
						<!-- Footer -->
							<%= render "partials/footer" unless @disable_footer%>

			</div>

		<!-- Scripts -->
			<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

	</body>
</html>

app/views/pages/about.html.haml
%article.post
  %header#about_page
    .title
      %h3 A blogging platform created by Sampad Medda.
      %h3 Hope you like it!

app/views/pages/contact.html.haml
%article.post
  %header#about_page
    .title
      %h3 Email : sampadmedda@gmail.com
      %h3 Phone : (+91) 9739570352

app/views/pages/resources.html.haml
%article.post
  %header#about_page
    .title
      %h3 This is resource dummy.
      %h3 I would like to keep wallpapers here.

app/views/partials/_footer.html.erb
<section id="footer">
								<ul class="icons">
									<li><a href="#" class="fa-twitter"><span class="label">Twitter</span></a></li>
									<li><a href="#" class="fa-facebook"><span class="label">Facebook</span></a></li>
									<li><a href="#" class="fa-instagram"><span class="label">Instagram</span></a></li>
									<li><a href="#" class="fa-rss"><span class="label">RSS</span></a></li>
									<li><a href="#" class="fa-envelope"><span class="label">Email</span></a></li>
								</ul>
								<p class="copyright">&copy; Untitled. Design: <a href="http://html5up.net">HTML5 UP</a>. Images: <a href="http://unsplash.com">Unsplash</a>.</p>
							</section>

					</section>

app/views/partials/_header.html.erb
<!DOCTYPE HTML>
<!--
	Future Imperfect by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>WebBlog</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
	</head>



	<body>

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<h1><a href="/">WebBlog</a></h1>
						<nav class="links">
							<ul>
								<li><%= link_to "Home", root_path %></li>
								<li><%= link_to "About", about_path%></li>
								<li><%= link_to "Blog", posts_path%></li>
								<li><%= link_to "Contact", contact_path%></li>
								<li><%= link_to "Resources", resources_path%></li>
							</ul>
						</nav>
						<nav class="main">

							<ul>

								<li class="search">
									<a class="fa-search" href="#search">Search</a>
								  <%= search_form_for @search,html: { id: "search"} do |f| %>


									<%= f.text_field :title_or_body_cont, placeholder: "Search sampy"  %>

									<%= f.submit "Search", id: "search" %>

								<%end %>
								</li>

								 <li class="menu">
									<a class="fa-bars" href="#menu">Menu</a>
								</li>
							</ul>
						</nav>
					</header>

app/views/partials/_pagination.html.erb
<ul class="actions pagination">
								<li><a href="" class="disabled button big previous">Previous Page</a></li>
								<li><a href="#" class="button big next">Next Page</a></li>
							</ul>

app/views/partials/_sidebar.html.erb
					<section id="sidebar">

						<!-- Intro -->
							<section id="intro">
								<a href="#" class="logo"> <%= image_tag "logo.jpg" %></a>
								<header>
									<h2>Perfect Blogging</h2>
									<p>Express your emotions to your Heart's Content.</p>
									<p id="nameIntro">By Sampad Medda</p>
								</header>
							</section>

							<!-- Posts List -->

								<section>
									<header>
										<h3>Trending Categories</h3>
									</header>

									<ul class="posts">
										<% all_trendingCategories.each do |cat| %>
											<li>
												<article>
													<header >
														<h3>
															<%= link_to cat.name, category_path(:id=>cat.id) %>
														</h3>
													</header>
												</article>
											</li>
											<% end %>

											<li>
												<article>
													<header >
														<h3>
															<%= link_to "... View More", categories_path %>
														</h3>
													</header>
												</article>
											</li>
									</ul>
								</section>

						<!-- Mini Posts -->
							<section>
								<header>
									<h3> trending posts </h3>
								</header>
								<div class="mini-posts">

									<!-- Mini Post -->

									<% all_trendingPosts.each do |trending| %>
										<article class="mini-post">
											<header>
												<h3><%= link_to trending.title, trending %></h3>
												<time class="published"><%= trending.created_at.strftime("%b %d, %Y") %></time>
												<a href="#" class="author"><<%= image_tag "avatar.jpg" %></a>
											</header>
											<a href="#" class="image"><%= image_tag "pic04.jpg" %></a>
										</article>
										<% end %>

								</div>
							</section>



						<!-- About -->
							<section class="blurb">
								<h2>About</h2>
								<p>This is a blogging platform where users can share articles just about anything. From everlasting memories to scariest of the experiences. Bring out the creative talent and jot down awesome articles.</p>
								<ul class="actions">
									<li><a href="/about" class="button">Learn More</a></li>
								</ul>
							</section>

app/views/posts/index.html.haml
%h1 Blog Posts

-@posts.each do |p|
 = link_to p.title, p
 %br
 
 =p.body
 %br
 %hr

//= link_to "Add new post", new_post_path

app/views/posts/show.html.haml
%article#singlepost.post
  %header
    .title
      %h2
        = @posts.title
      %p Lorem ipsum dolor amet nullam consequat etiam feugiat
    .meta
      %time.published
        = @posts.created_at.strftime("%b %d, %Y")
      %a.author{:href => "#"}
        %span.name
          = @posts.admin_user.name
        %img
          = image_tag "avatar.jpg"
  %span.image.featured
    %img
      = image_tag "pic01.jpg"
  %p
    = @posts.body
  %p Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at. Phasellus sed ultricies mi non congue ullam corper. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.
  %p Nunc quis dui scelerisque, scelerisque urna ut, dapibus orci. Sed vitae condimentum lectus, ut imperdiet quam. Maecenas in justo ut nulla aliquam sodales vel at ligula. Sed blandit diam odio, sed fringilla lectus molestie sit amet. Praesent eu tortor viverra lorem mattis pulvinar feugiat in turpis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce ullamcorper tellus sit amet mattis dignissim. Phasellus ut metus ligula. Curabitur nec leo turpis. Ut gravida purus quis erat pretium, sed pellentesque massa elementum. Fusce vestibulum porta augue, at mattis justo. Integer sed sapien fringilla, dapibus risus id, faucibus ante. Pellentesque mattis nunc sit amet tortor pellentesque, non placerat neque viverra.

  %p
    = link_to "Back to all Posts", posts_path
  %footer
    %ul.stats
      %li
        = link_to @posts.category.name, category_path(:id => @posts.category.id)
      %li
        %a.icon.fa-heart{:href => "#"} 28
      %li
        %a.icon.fa-comment{:href => "#"} 128